# SyncSub Configuration

# --- Paths ---
# Temporary directory MUST exist. Use forward slashes or double backslashes.
temp_dir: "E:/syncsub_temp/"
log_dir: "logs"
log_file: "syncsub.log"

# --- Processing ---
# Device: "cuda" for GPU (recommended), "cpu" for CPU
device: "cuda"

# --- Audio Extraction ---
# ffmpeg_path: null # Set path only if ffmpeg is not in your system PATH

# --- Transcription (Whisper) ---
# Models: tiny, base, small, medium, large, large-v2, large-v3
# See https://github.com/openai/whisper#available-models-and-languages
whisper_model: "small.en" # Use english-only model for better performance if source is always english
# fp16: true # Set to false if your GPU doesn't support float16
whisper_fp16: true

# --- Translation (Hugging Face) ---
# Find models at https://huggingface.co/models?pipeline_tag=translation
# Ensure the model handles English ('en') to Malayalam ('ml')
translation_model: "Helsinki-NLP/opus-mt-en-ml"

# --- Subtitle Formatting ---
# Output format: "srt" or "vtt" (Currently only SRT implemented)
output_format: "srt"
# Segmentation rules
max_chars_per_segment: 80   # Max characters before trying to split a line
max_duration_seconds: 7     # Max duration of a single subtitle block
max_lines_per_block: 2      # Max number of lines in a single subtitle block